export default class CreditScreen extends Phaser.Scene {
    
    public content: string[] = [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "$TRUMP presents",
        "",
        "A tremendous production",
        "",
        "Trump's Great Escape!",
        "",
        "",
        "Lead Cast",
        "47",
        "45",
        "44",
        "46",
        "Gary",
        "Sam",
        
        "",
        "Supporting Cast",
        "Hoes",
        "",
        "Casting Director",
        "DandyBanger",
        "Han Ball",
        "",
        "Music Composer",
        "Loony chitptoon",
        "Public Domain",
        "jsfxr",
        "",
        "Costume Designer",
        "Miley Cyrus",
        "",
        "Associate Producers",
        "Juan Concreto",
        "",
        "Editors",
        "The Lost Hyenas",
        "",
        "Production Designer",
        "Ninkwondo",
        "",
        "Director of Photography",
        "DandyBanger",
        "",
        "Executive Producer",
        "Crypto King",
        "",
        "Voice Over",
        "Ms. Krasota",
        "CryptoSeas",
        "",
        "Writers",
        "DTrumpERC20",
        "HanBall",
        "DandyBanger",
        "",
        "Director",
        "CZ",
        "",
        "Game Designer",
        "DTrumpERC20",
        "HanBall",
        "DandyBanger",
        "",
        "Sound engineer",
        "Retro OpenGame Art",
        "FreeSound",
        "",
        "Musical Composition",
        "Nicole Marie T",
        "BGM The Slimeking's Tower",
        "DeltaBreaker",
        "Bottomless Pit Man",
        "@wyver9",
        "Snabisch http://audiojungle.net/user/Snabisch",
        "Mega Pixel Music Lab",
        "Christovix",
        "Kim Lightyear",
        "3xBlast",
        "Trevor Lentz",
        "(SubspaceAudio) Juhani Junkala",
        "Tad Miller",
        "Nene",
        "SketchyLogic",
        "Spring Spring",
        "shiru8bit",
        "marcelofg55",
        "celestialghost8",
        "IgnasD",
        "congusbongus",
        "Centurion_of_war",
        "",
        "",
        "#LETSMAKEMEMESGREATAGAIN",
        "$TRUMP",

    ];

    constructor(name: string)  {
        super(name);
    }

   
}